spring:
  application:
    name: backoffice-api

  datasource:
    url: jdbc:postgresql://${DB_HOST:aws-1-us-east-2.pooler.supabase.com}:${DB_PORT:5432}/${DB_NAME:postgres}
    username: ${DB_USERNAME:postgres.igwrcahikcdgnwuzwxhh}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    try-it-out-enabled: true
  api-docs:
    path: /v3/api-docs

app:
  jwt:
    secret: ${JWT_SECRET:404D635166546A576E5A7234753778214125442A472D4B6150645367566B5970}
    expiration: ${JWT_EXPIRATION:86400000}
  rate-limiter:
    max-requests: ${RATE_LIMITER_MAX_REQUESTS:60}
    window-size-seconds: ${RATE_LIMITER_WINDOW_SECONDS:60}
